# Generated by Django 3.0.5 on 2020-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageDetection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplocation',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='images',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='total_free',
            field=models.IntegerField(default=0),
        ),
    ]
